### ISSUE TITLE
Where is label for phase recognition ??

### ISSUE THREAD

**Issue by shinpaul14** [IMSY-DKFZ/self-distilled-swin#1]
How can we train the model with multi-task learning, phase-recognition.

in the train.py there is code where it loads 

`from multihead import *
from multihead_phaseprediction import *`

However, in the code there isn't multihead .py or multihead_phaseprediction .py

**Comment by Amiiney** [comment]
Hi @shinpaul14 The phase recognition labels were parsed from the Cholec80 dataset, we will release a csv file with the annotations or the preprocessing code. I'll give an update in this issue.

**Comment by Amiiney** [comment]
The preprocessing instructions to generate the phase annotations are added to the README:

### **Cholec80:** (Phase annotations)
The surgical phase annotations are parsed from cholec80 dataset, you can download the dataset following the instructions in the [cholec80 dataset's repository](https://github.com/CAMMA-public/TF-Cholec80).

After downloading the dataset, set the path to the phase annotations folder `cholec80_phase_path` in the config.yaml

```
cholec80_phase_path: local_path/cholec80/phase_annotations
```
