### ISSUE TITLE
Question about the SwinT+Multi

### ISSUE THREAD

**Issue by shinpaul14** [IMSY-DKFZ/self-distilled-swin#4]
Hello, Thank you for releasing the code with clear instructions!

I have a question about "SwinT+Multi". In the paper, it was mentioned that phase recognition information is required for training the "SwinT+Multi" model. However, in the code documentation and instructions provided, there seems to be no mention or requirement of phase recognition information for reproducing the "SwinT+Multi" results.

please let me know if I miss understood  "SwinT+Multi"

Best

**Comment by Amiiney** [comment]
Hi @shinpaul14,
In that section we wanted to introduce all the extra annotations used, including the phase, however, in the ensemble section we explained that the main SwinT used instrument, verb and target only while the phase was added as one component of the ensemble, which means that the phase model is needed only in the ensemble and not in the the rest of experiments.

Best,
