### ISSUE TITLE
"Inquiry Regarding the Utilization of mAP or cmAP Metrics in Your Research"

### ISSUE THREAD

**Issue by xhdr0618** [IMSY-DKFZ/self-distilled-swin#7]
Thank you very much for your open-source code and paper. May I ask whether the mAP used in your paper refers to the mAP metric or the cmAP metric?

**Comment by Amiiney** [comment]
Hi @xhdr0618, the metric used in the paper is cmAP which uses the same aggregation scheme as in ivtmetrics and the rendezvous baseline.
The mAP metric (without aggregation) is used as a complementary metric.

**Comment by xhdr0618** [comment]
mail.scut.edu.cn

**Comment by xhdr0618** [comment]
Thank you very much for your answer.
