### ISSUE TITLE
How can we reproduce the challenge results?

### ISSUE THREAD

**Issue by shinpaul14** [IMSY-DKFZ/self-distilled-swin#8]
With this codebase how can we reproduce the CholecTriplet 2022 test set result?

**Comment by Amiiney** [comment]
At the time of publishing the paper, the cholectriplet test set was still hidden. We sent our docker to the organizers who run the inference on the test set and shared the results with us. The [CholecT50 dataset](https://github.com/CAMMA-public/cholect50) is now public, but you have to verify with the authors which videos and triplets were included in the final evaluation.
We plan to add an inference script for the test set to this codebase in the future.
